# Generated by Django 6.1.1 on 2026-09-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tags',
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(choices=[('delivery_rider', 'Delivery rider'), ('taxi', 'Taxi'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
