# Generated by Django 6.1.1 on 2026-09-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], default='fi', max_length=2, verbose_name='message language'),
        ),
        migrations.AlterField(
            model_name='client',
            name='opted_out',
            field=models.BooleanField(default=False, help_text='Skipped automatically when sending.', verbose_name='opted out of messages'),
        ),
    ]
