# Generated by Django 6.1.1 on 2026-09-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=10)),
                ('subject_fi', models.CharField(blank=True, max_length=200, verbose_name='subject (Finnish)')),
                ('body_fi', models.TextField(blank=True, verbose_name='message (Finnish)')),
                ('subject_en', models.CharField(blank=True, max_length=200, verbose_name='subject (English)')),
                ('body_en', models.TextField(blank=True, verbose_name='message (English)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=10)),
                ('subject_fi', models.CharField(blank=True, max_length=200)),
                ('body_fi', models.TextField(blank=True)),
                ('subject_en', models.CharField(blank=True, max_length=200)),
                ('body_en', models.TextField(blank=True)),
                ('due_date', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('done', 'Done')], default='queued', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('skipped_opted_out', models.PositiveIntegerField(default=0)),
                ('skipped_no_address', models.PositiveIntegerField(default=0)),
                ('test_mode', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=10)),
                ('language', models.CharField(choices=[('fi', 'Finnish'), ('en', 'English')], max_length=2)),
                ('to_address', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='messaging_m_campaig_75e4de_idx'), models.Index(fields=['client', '-created_at'], name='messaging_m_client__79c52f_idx')],
            },
        ),
    ]
