# Generated by Django 6.1.1 on 2026-09-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sms_parts',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many SMS this message used (0 for email).', verbose_name='SMS parts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
    ]
