# Generated by Django 6.1.1 on 2026-09-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='via_provider',
            field=models.BooleanField(default=False, help_text='Handed to the real provider (not only printed or logged).'),
        ),
    ]
