# Generated by Django 6.1.1 on 2026-09-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_via_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered_to',
            field=models.CharField(blank=True, help_text='Where it really went. Differs from to_address in test mode; empty if only printed or logged.', max_length=254),
        ),
    ]
