# Generated by Django 6.1.1 on 2026-09-29 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_delivered_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('title', 'channel'), name='unique_template_title_per_channel'),
        ),
    ]
