# Generated by Django 6.1.1 on 2026-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
